[package]
name = "svgtextbox"
version = "0.1.0"
authors = ["Tom McLean <thomasowenmclean@gmail.com>"]
edition = "2018"

[dependencies]
cairo-rs = {version = "0.6.0", features = ["svg"]}
pango = "~0.6"
pangocairo = "~0.7"
base64 = "0.10.1"