[package]
name = "svgtextbox"
version = "0.1.0"
authors = ["Tom McLean <thomasowenmclean@gmail.com>"]
edition = "2018"
license = "LGPL-3.0-or-later"

[dependencies]
cairo-rs = {version = "0.6.0", features = ["svg"]}
pango = "~0.6"
pangocairo = "~0.7"
base64 = "0.10.1"
regex = "1.1.5"
glib = "~0.7"
pango-sys = "~0.8"
custom_error = "1.6.0"
minidom = "~0.10"
quick-xml = "~0.13"

[dev-dependencies]
proptest = "0.9.2"